# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6df05fc370c5a83bd3210f7e34b1e75d"
name = "promo-banner-app"
application_url = "https://16ec7c363ad3.ngrok-free.app/"
embedded = true
handle = "promo-banner-app-10"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://16ec7c363ad3.ngrok-free.app//auth/callback", "https://16ec7c363ad3.ngrok-free.app//auth/shopify/callback", "https://16ec7c363ad3.ngrok-free.app//api/auth/callback"]

[pos]
embedded = false
